"""update model

Revision ID: 651212c20ec6
Revises: ff2170395f36
Create Date: 2026-09-02 15:59:44.774183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '651212c20ec6'
down_revision: Union[str, Sequence[str], None] = 'ff2170395f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'status')
    op.drop_column('characters', 'injuries')
    op.drop_column('characters', 'wardrobe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('wardrobe', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('injuries', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
