"""add scene character and prop relationships

Revision ID: ef82609ddb84
Revises: fb254519abef
Create Date: 2026-08-30 14:17:26.567904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef82609ddb84'
down_revision: Union[str, Sequence[str], None] = 'fb254519abef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_characters',
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_id', 'character_id')
    )
    op.create_table('scene_props',
    sa.Column('scene.id', sa.Integer(), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prop_id'], ['props.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene.id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene.id', 'prop_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_props')
    op.drop_table('scene_characters')
    # ### end Alembic commands ###
